-- ============================================================================
-- ORDER REFERENCE CODE (URA-NNNN-AA)
--
-- Adds a human-readable reference code (e.g. URA-5829-XQ) generated by the
-- backend on every new order. Code is generated atomically inside
-- create_order_with_items with retry-on-collision against a partial UNIQUE
-- index. Existing orders are NOT backfilled — column stays nullable so old
-- rows simply have no code.
--
-- Format: 'URA-' + 4 digits + '-' + 2 uppercase letters  (~6.76M combinations)
-- ============================================================================

ALTER TABLE orders ADD COLUMN reference_code TEXT;

CREATE UNIQUE INDEX IF NOT EXISTS orders_reference_code_key
  ON orders (reference_code)
  WHERE reference_code IS NOT NULL;

CREATE OR REPLACE FUNCTION public._gen_order_reference_code()
RETURNS TEXT
LANGUAGE plpgsql
AS $function$
DECLARE
  v_digits TEXT;
  v_letters TEXT;
BEGIN
  v_digits := lpad((floor(random() * 10000))::int::text, 4, '0');
  v_letters := chr(65 + floor(random() * 26)::int) ||
               chr(65 + floor(random() * 26)::int);
  RETURN 'URA-' || v_digits || '-' || v_letters;
END;
$function$;

-- ── ATOMIC ORDER CREATION (now with reference_code) ─────────────────────────
-- Replaces the function defined in 20260519_atomic_order_creation_and_zero_item_guards.sql
-- Adds reference code generation with retry-on-collision (up to 10 attempts).
-- 0-item / direction / item insertion logic preserved byte-for-byte.

CREATE OR REPLACE FUNCTION public.create_order_with_items(
  p_direction TEXT,
  p_entity_id UUID,
  p_rep_id UUID DEFAULT NULL,
  p_notes TEXT DEFAULT NULL,
  p_items JSONB DEFAULT '[]'::jsonb
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $function$
DECLARE
  v_order_id UUID;
  v_item JSONB;
  v_inv_id UUID;
  v_current_qty INT;
  v_was_unavailable BOOLEAN;
  v_code TEXT;
  v_attempt INT;
BEGIN
  -- Authentication check: must be an approved user.
  IF NOT EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND is_approved = TRUE) THEN
    RETURN jsonb_build_object('success', false, 'error', 'غير مصرح');
  END IF;

  -- Reject empty orders. No exceptions.
  IF p_items IS NULL OR jsonb_array_length(p_items) = 0 THEN
    RETURN jsonb_build_object('success', false, 'error', 'يجب إضافة عنصر واحد على الأقل للطلب');
  END IF;

  -- Validate direction.
  IF p_direction NOT IN ('outbound', 'inbound_rep', 'inbound_external') THEN
    RETURN jsonb_build_object('success', false, 'error', 'اتجاه الطلب غير صالح');
  END IF;

  -- Generate reference code; retry on UNIQUE collision. 6.76M keyspace makes
  -- collisions vanishingly rare, but we retry to be safe.
  v_attempt := 0;
  LOOP
    v_attempt := v_attempt + 1;
    v_code := public._gen_order_reference_code();
    BEGIN
      INSERT INTO orders (direction, entity_id, rep_id, status, notes, created_by, assigned_at, reference_code)
      VALUES (
        p_direction::order_direction,
        p_entity_id,
        p_rep_id,
        'assigned'::order_status,
        NULLIF(p_notes, ''),
        auth.uid(),
        NOW(),
        v_code
      )
      RETURNING id INTO v_order_id;
      EXIT;
    EXCEPTION WHEN unique_violation THEN
      IF v_attempt >= 10 THEN
        RETURN jsonb_build_object('success', false, 'error', 'فشل توليد الرمز المرجعي');
      END IF;
    END;
  END LOOP;

  -- Insert each item with was_unavailable_at_creation flag set from current inventory.
  FOR v_item IN SELECT * FROM jsonb_array_elements(p_items) LOOP
    v_inv_id := NULLIF(v_item->>'inventory_id', '')::UUID;
    v_was_unavailable := FALSE;

    IF v_inv_id IS NOT NULL THEN
      SELECT quantity INTO v_current_qty FROM inventory WHERE id = v_inv_id;
      v_was_unavailable := COALESCE(v_current_qty, 0) = 0;
    END IF;

    INSERT INTO order_items (
      order_id,
      inventory_id,
      quantity,
      is_custom,
      custom_description,
      source_inventory_id,
      was_unavailable_at_creation
    ) VALUES (
      v_order_id,
      v_inv_id,
      (v_item->>'quantity')::INT,
      COALESCE((v_item->>'is_custom')::BOOLEAN, FALSE),
      v_item->>'custom_description',
      NULLIF(v_item->>'source_inventory_id', '')::UUID,
      v_was_unavailable
    );
  END LOOP;

  RETURN jsonb_build_object('success', true, 'order_id', v_order_id, 'reference_code', v_code);
END;
$function$;
